// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE9_DPlzjspuhM8yjV6PDtgtU1VQcre7k',
    appId: '1:237507548270:web:f80d6bb0e8081cbb6dc27f',
    messagingSenderId: '237507548270',
    projectId: 'babynourish-3ca74',
    authDomain: 'babynourish-3ca74.firebaseapp.com',
    storageBucket: 'babynourish-3ca74.firebasestorage.app',
    measurementId: 'G-BLPCYBYQTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWb_7rxQHpbngPzJSA39MKh20b5EsSlw',
    appId: '1:237507548270:android:8df6d4be9b9c61616dc27f',
    messagingSenderId: '237507548270',
    projectId: 'babynourish-3ca74',
    storageBucket: 'babynourish-3ca74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy4deUpQmvL4rikvJyRVRyRHHkNnHQzwM',
    appId: '1:237507548270:ios:69eec858ec23d2b86dc27f',
    messagingSenderId: '237507548270',
    projectId: 'babynourish-3ca74',
    storageBucket: 'babynourish-3ca74.firebasestorage.app',
    iosBundleId: 'com.example.nourishBabyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy4deUpQmvL4rikvJyRVRyRHHkNnHQzwM',
    appId: '1:237507548270:ios:69eec858ec23d2b86dc27f',
    messagingSenderId: '237507548270',
    projectId: 'babynourish-3ca74',
    storageBucket: 'babynourish-3ca74.firebasestorage.app',
    iosBundleId: 'com.example.nourishBabyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCE9_DPlzjspuhM8yjV6PDtgtU1VQcre7k',
    appId: '1:237507548270:web:8af98c0ca06be3876dc27f',
    messagingSenderId: '237507548270',
    projectId: 'babynourish-3ca74',
    authDomain: 'babynourish-3ca74.firebaseapp.com',
    storageBucket: 'babynourish-3ca74.firebasestorage.app',
    measurementId: 'G-CXK247HGC5',
  );
}
